# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 599d7e1fbe52741f9c4359fc707f9f54d0be2f2e7148c468a803825bb4735e1f666a83d5d5e970b4c4075c9ccf6355dc0bb4649a14a13d792607def5ef7fb651

test:
  secret_key_base: ff3d44fdd6594c405bf7d804f20d02e19b0c2c64c6a4889b8d6e36bf78b9e7a16c5159d3f05372d582868cb9e091d9d16bb48b28101072dbe0e5994ac8b8f452

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
